# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyhscore',
                'doc_host': 'https://IntegratedPathologyUnit-ICR.github.io',
                'git_url': 'https://github.com/IntegratedPathologyUnit-ICR/pyhscore',
                'lib_path': 'pyhscore'},
  'syms': {'pyhscore.core': {'pyhscore.core.foo': ('core.html#foo', 'pyhscore/core.py')}}}
